### ISSUE TITLE
Object.require is deprecated.

### ISSUE THREAD

**Issue by NeelkanthMehta** [greyatom-edu-tech/greyatom-ide#11]
Use `remote.BrowserWindow` instead of `remote.require("browser-window")`
```
Object.require (/Applications/Commit Live.app/Contents/Resources/app.asar/src/electron-shims.js:54:12)
Object.<anonymous> (/Users/neelkanthmehta/.atom/packages/greyatom-ide/lib/notifier.coffee:24:26)
Object.<anonymous> (/Users/neelkanthmehta/.atom/packages/greyatom-ide/lib/notifier.coffee:146:4)
Module._compile (/Applications/Commit Live.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
Object..coffee (/Applications/Commit Live.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
Module.load (module.js:473:32)
```

**Comment by manishnk09** [comment]
Object.require - /Applications/Commit Live 2.app/Contents/Resources/app.asar/src/electron-shims.js:54:12
Object.<anonymous> - /Users/manishkembral/.atom/packages/greyatom-ide/lib/notifier.coffee:24:26
Object.<anonymous> - /Users/manishkembral/.atom/packages/greyatom-ide/lib/notifier.coffee:146:4
Module._compile - /Applications/Commit Live 2.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30
Object..coffee - /Applications/Commit Live 2.app/Contents/Resources/app.asar/src/compile-cache.js:216:21
Module.load - module.js:473:32
